-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 14:28:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDCAMPUS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDCAMPUS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDCAMPUS` DEFAULT CHARACTER SET utf8 ;
USE `BDCAMPUS` ;

-- -----------------------------------------------------
-- Table `BDCAMPUS`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`administrador` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`administrador` (
  `idadministrador` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` INT NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`alumno` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`alumno` (
  `idalumno` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` INT NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`Pagos` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`Pagos` (
  `idPagos` INT NOT NULL,
  `nombrepago` VARCHAR(45) NOT NULL,
  `monto` DOUBLE NOT NULL,
  `tipomoneda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`matricula` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`matricula` (
  `idmatricula` INT NOT NULL,
  `ciclo` VARCHAR(45) NOT NULL,
  `seccion` VARCHAR(45) NOT NULL,
  `administrador_idadministrador` INT NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  `Pagos_idPagos` INT NOT NULL,
  PRIMARY KEY (`idmatricula`),
  INDEX `fk_matricula_administrador_idx` (`administrador_idadministrador` ASC),
  INDEX `fk_matricula_alumno1_idx` (`alumno_idalumno` ASC),
  INDEX `fk_matricula_Pagos1_idx` (`Pagos_idPagos` ASC),
  CONSTRAINT `fk_matricula_administrador`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `BDCAMPUS`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `BDCAMPUS`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_Pagos1`
    FOREIGN KEY (`Pagos_idPagos`)
    REFERENCES `BDCAMPUS`.`Pagos` (`idPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`curso` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`curso` (
  `idcurso` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`profesor` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`profesor` (
  `idprofesor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sexo` INT NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprofesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`horario` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`horario` (
  `idhorario` INT NOT NULL,
  `fechainicio` VARCHAR(45) NOT NULL,
  `fechafin` VARCHAR(45) NOT NULL,
  `horainicio` VARCHAR(30) NOT NULL,
  `horafin` VARCHAR(45) NOT NULL,
  `profesor_idprofesor` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idhorario`),
  INDEX `fk_horario_profesor1_idx` (`profesor_idprofesor` ASC),
  INDEX `fk_horario_curso1_idx` (`curso_idcurso` ASC),
  CONSTRAINT `fk_horario_profesor1`
    FOREIGN KEY (`profesor_idprofesor`)
    REFERENCES `BDCAMPUS`.`profesor` (`idprofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `BDCAMPUS`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`matricula_has_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`matricula_has_curso` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`matricula_has_curso` (
  `matricula_idmatricula` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`matricula_idmatricula`, `curso_idcurso`),
  INDEX `fk_matricula_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_matricula_has_curso_matricula1_idx` (`matricula_idmatricula` ASC),
  CONSTRAINT `fk_matricula_has_curso_matricula1`
    FOREIGN KEY (`matricula_idmatricula`)
    REFERENCES `BDCAMPUS`.`matricula` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `BDCAMPUS`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`asistencia` (
  `idasistencia` INT NOT NULL,
  `asistencia` VARCHAR(45) NOT NULL,
  `matricula_has_curso_matricula_idmatricula` INT NOT NULL,
  `matricula_has_curso_curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idasistencia`),
  INDEX `fk_asistencia_matricula_has_curso1_idx` (`matricula_has_curso_matricula_idmatricula` ASC, `matricula_has_curso_curso_idcurso` ASC),
  CONSTRAINT `fk_asistencia_matricula_has_curso1`
    FOREIGN KEY (`matricula_has_curso_matricula_idmatricula` , `matricula_has_curso_curso_idcurso`)
    REFERENCES `BDCAMPUS`.`matricula_has_curso` (`matricula_idmatricula` , `curso_idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`notas` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`notas` (
  `idnotas` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `tiponota` VARCHAR(45) NOT NULL,
  `matricula_has_curso_matricula_idmatricula` INT NOT NULL,
  `matricula_has_curso_curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idnotas`),
  INDEX `fk_notas_matricula_has_curso1_idx` (`matricula_has_curso_matricula_idmatricula` ASC, `matricula_has_curso_curso_idcurso` ASC),
  CONSTRAINT `fk_notas_matricula_has_curso1`
    FOREIGN KEY (`matricula_has_curso_matricula_idmatricula` , `matricula_has_curso_curso_idcurso`)
    REFERENCES `BDCAMPUS`.`matricula_has_curso` (`matricula_idmatricula` , `curso_idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`Laboratorio` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idLaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`ReservaLaboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`ReservaLaboratorio` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`ReservaLaboratorio` (
  `idReservaLaboratorio` INT NOT NULL,
  `horainicio` VARCHAR(45) NOT NULL,
  `horafin` VARCHAR(45) NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  `Laboratorio_idLaboratorio` INT NOT NULL,
  PRIMARY KEY (`idReservaLaboratorio`),
  INDEX `fk_ReservaLaboratorio_alumno1_idx` (`alumno_idalumno` ASC),
  INDEX `fk_ReservaLaboratorio_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC),
  CONSTRAINT `fk_ReservaLaboratorio_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `BDCAMPUS`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservaLaboratorio_Laboratorio1`
    FOREIGN KEY (`Laboratorio_idLaboratorio`)
    REFERENCES `BDCAMPUS`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`Actividad` (
  `idActividad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`ReservaActividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`ReservaActividad` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`ReservaActividad` (
  `idReservaActividad` INT NOT NULL,
  `dia` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`idReservaActividad`),
  INDEX `fk_ReservaActividad_alumno1_idx` (`alumno_idalumno` ASC),
  INDEX `fk_ReservaActividad_Actividad1_idx` (`Actividad_idActividad` ASC),
  CONSTRAINT `fk_ReservaActividad_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `BDCAMPUS`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservaActividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `BDCAMPUS`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`Libro` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`Libro` (
  `idLibro` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `ejemplares` INT NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`ReservaLibro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`ReservaLibro` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`ReservaLibro` (
  `idReservaLibro` INT NOT NULL,
  `fechaentrega` VARCHAR(45) NOT NULL,
  `fechadevolucion` VARCHAR(45) NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  `Libro_idLibro` INT NOT NULL,
  PRIMARY KEY (`idReservaLibro`),
  INDEX `fk_ReservaLibro_alumno1_idx` (`alumno_idalumno` ASC),
  INDEX `fk_ReservaLibro_Libro1_idx` (`Libro_idLibro` ASC),
  CONSTRAINT `fk_ReservaLibro_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `BDCAMPUS`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservaLibro_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `BDCAMPUS`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`recursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`recursos` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`recursos` (
  `idrecursos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `horario_idhorario` INT NOT NULL,
  PRIMARY KEY (`idrecursos`),
  INDEX `fk_recursos_horario1_idx` (`horario_idhorario` ASC),
  CONSTRAINT `fk_recursos_horario1`
    FOREIGN KEY (`horario_idhorario`)
    REFERENCES `BDCAMPUS`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDCAMPUS`.`anuncios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDCAMPUS`.`anuncios` ;

CREATE TABLE IF NOT EXISTS `BDCAMPUS`.`anuncios` (
  `idanuncios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horario_idhorario` INT NOT NULL,
  PRIMARY KEY (`idanuncios`),
  INDEX `fk_anuncios_horario1_idx` (`horario_idhorario` ASC),
  CONSTRAINT `fk_anuncios_horario1`
    FOREIGN KEY (`horario_idhorario`)
    REFERENCES `BDCAMPUS`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
